# Generated by Django 3.0.8 on 2020-08-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0005_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
